language: node_js
node_js:
  - '4'
dist: trusty # Chrome Headless needs Ubuntu Trusty on Travis
sudo: false
addons:
  chrome: stable
script: npm run ci-test
notifications:
  slack:
    secure: f5QSFkke3kvTa0Li+PT5qgFozTmY0inw0PPWJn5FXeg+P1PGIG4ksL8ACKxtwO+repbrdrLYX9kt/AQaLnktXXvuylgI5wqt+YQYIwTP8WV91SkBVJotz4+0UxRk0O47lM/IGBSV5lU6Oon0gr8zz4PPwpZw4xjWEinWmWi+ZLo=
    on_success: change
